Blog/urls.py
from django.urls import path

from . import views

app_name = 'Blog'

urlpatterns = [
    path('', views.CreatePosts.as_view(), name='create_post'),
    path('update/<int:pk>/', views.UpdatePosts.as_view(), name='update_post'),
    path('list/', views.ListPost.as_view(), name='list_posts'),
    path('list/<int:pk>/', views.PostDetail.as_view(), name='detail_post'),
    path('list/<int:pk>/comment/', views.CreateComment.as_view(), name='comment'),
    path('feedback/', views.ContactToAdmin.as_view(), name='feedback')
]

core/urls.py
from Blog import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/<int:pk>/', views.PublicProfile.as_view(), name='profile'),
    path("accounts/register/", views.RegisterFormView.as_view(), name="register"),
    path('accounts/<int:pk>/update/', views.UpdateProfile.as_view(), name='profile_update'),

    path('blog/', include('Blog.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
    path('__debug__/', include(debug_toolbar.urls))
        ]

Blog/models.py
from django.contrib.auth.models import User
from django.db import models


class Posts(models.Model):
    subject = models.CharField(max_length=40)
    text = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    image = models.ImageField(blank=True)
    synopsis = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.date.date()}, {self.date.time()}'


class Comments(models.Model):
    comment = models.CharField(max_length=150)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.comment

Blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Comments, Posts



class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Posts
        widgets = {
            'text': forms.Textarea,
            'synopsis': forms.Textarea,
        }
        fields = ('subject', 'synopsis', 'text', 'is_published', 'image',)


class AdminPostsForm(forms.ModelForm):
    class Meta:
        model = Posts
        widgets = {
            'text': forms.Textarea,
            'synopsis': forms.Textarea
        }
        fields = ('owner', 'synopsis', 'text', 'subject', 'image')


class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        widgets = {
            'comment': forms.Textarea,
        }
        fields = ('comment', )


class AdminCommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        widgets = {
            'comment': forms.Textarea,
        }
        fields = ('comment', 'author', 'is_published')


class ContactToAdminForm(forms.Form):
    subject = forms.CharField(max_length=30)
    message = forms.CharField(max_length=200)

Blog/views.py
from core import settings

from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth import mixins
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin

from .forms import ContactToAdminForm, CreateCommentForm, CreatePostForm, RegisterForm
from .models import Comments, Posts
from .tasks import send_massage


class RegisterFormView(generic.FormView):
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy("Blog:list_posts")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    

class CreatePosts(mixins.LoginRequiredMixin, generic.FormView):
    template_name = 'Blog/create_post_view.html'
    form_class = CreatePostForm
    success_url = reverse_lazy("Blog:create_post")

    def form_valid(self, form):
        Posts.objects.create(owner=User.objects.get(username=self.request.user),
                             text=form.cleaned_data["text"],
                             subject=form.cleaned_data["subject"],
                             synopsis=form.cleaned_data['synopsis'],
                             image=form.cleaned_data['image'],
                             is_published=form.cleaned_data['is_published']
                             )
        send_massage.apply_async(args=['new message',
                                       settings.EMAIL_HOST_USER, 'New Post'])
        return super().form_valid(form)


class UpdatePosts(mixins.LoginRequiredMixin, generic.UpdateView):
    template_name = 'Blog/update_posts_view.html'
    model = Posts
    form_class = CreatePostForm
    success_url = reverse_lazy("Blog:list_posts")

    def get_queryset(self):
        return Posts.objects.filter(pk=self.kwargs['pk']).filter(owner=self.request.user)


class ListPost(generic.ListView):
    template_name = 'Blog/list_post_view.html'
    model = Posts
    paginate_by = 15

    def get_queryset(self):
        return Posts.objects.select_related('owner').filter(is_published=True)


class PostDetail(generic.DetailView):
    model = Posts
    template_name = 'Blog/post_detail_view.html'

    def get_queryset(self):
        return Posts.objects.select_related('owner').prefetch_related('comments_set').\
            filter(pk=self.kwargs['pk']).filter(is_published=True)


class CreateComment(generic.FormView):
    form_class = CreateCommentForm
    template_name = 'Blog/create_comment_view.html'

    def form_valid(self, form):
        self.success_url = reverse_lazy('Blog:detail_post', kwargs={'pk': self.kwargs['pk']})
        Comments.objects.create(author=self.request.user,
                                comment=form.cleaned_data["comment"],
                                post=Posts.objects.get(pk=self.kwargs['pk'])
                                )
        send_massage.apply_async(args=['new message',
                                       settings.EMAIL_HOST_USER,
                                       'new message'])
        send_massage.apply_async(args=['new message',
                                       Posts.objects.get(pk=self.kwargs['pk']).owner.email,
                                       self.success_url])
        return super().form_valid(form)


class PublicProfile(generic.DetailView):
    model = User
    template_name = 'registration/public_profile_view.html'

    def get_queryset(self):
        return User.objects.prefetch_related('posts_set').filter(pk=self.kwargs['pk'])


class UpdateProfile(mixins.LoginRequiredMixin, generic.UpdateView):
    model = User
    template_name = 'registration/update_profile.html'
    fields = ('username', 'last_name', 'first_name', 'email')

    def get_queryset(self):
        return User.objects.filter(pk=self.kwargs['pk']).filter(username=self.request.user)

    def form_valid(self, form):
        self.success_url = reverse_lazy('profile', kwargs={'pk': self.kwargs['pk']})
        return super().form_valid(form)


class ContactToAdmin(mixins.LoginRequiredMixin, SuccessMessageMixin, generic.FormView):
    form_class = ContactToAdminForm
    template_name = 'Blog/contact_to_admin.html'
    success_url = reverse_lazy('Blog:feedback')
    success_message = 'Accepted'

    def get(self, request, *args, **kwargs):
        data = dict()
        data['html_form'] = render_to_string('Blog/contact_to_admin.html',  {'form': self.get_form()}, request=request)
        return JsonResponse(data)

    def form_valid(self, form):
        text = f'{form.cleaned_data["message"]} \n By {self.request.user}'
        send_massage.apply_async(args=[form.cleaned_data['subject'],
                                       settings.EMAIL_HOST_USER,
                                       text]
                                 )
        return super().form_valid(form)

Blog/templates/Blog/contact_to_admin.html
<body>

<form method="post" action="{% url 'Blog:feedback' %}" class="js-book-create-form">
    {% csrf_token %}
      <div class="modal-body">
    {{ form.as_p }}
      </div>
    {% if messages %}
<div class="alert alert-success">
    {% for m in messages %}
        <p>{{ m }}</p>
    {% endfor %}
</div>
{% endif %}
      <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Send</button>

  </div>
</form>
</body>

Blog/templates/Blog/create_comment_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="accept">
</form>


</body>
</html>

Blog/templates/Blog/create_post_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load static %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="accept">
</form>

</body>
</html>

Blog/templates/Blog/list_post_view.html
{% extends 'base.html' %}
{% load static %}



    {% block extra_js %}    {#бустреп в файле base.html #}
        <script src="{% static 'js/book.js' %}"></script>    {#js в статике. Позволяет нажать на кнопку#}
    {% endblock %}
{% block content %}

  <div class="modal fade" id="modal-book"> {#позволяет вызвать всплывающее окно #}
      <div class="modal-dialog">
      <div class="modal-content">

      </div>
    </div>
  </div>


{%  for i in object_list %}
    <p><a href="{% url 'Blog:detail_post' i.id%}"> {{ i.subject }}</a></p>
    <p>{{ i.synopsis }}</p>
    <p>{{ i.owner }}  {{ i.date }}</p>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

Blog/templates/Blog/post_detail_view.html
{% extends 'base.html' %}
{% load static %}

<body>

    {% block extra_js %}    {#бустреп в файле base.html #}
        <script src="{% static 'js/book.js' %}"></script>    {#js в статике. Позволяет нажать на кнопку#}
    {% endblock %}
{% block content %}
  <div class="modal fade" id="modal-book"> {#позволяет вызвать всплывающее окно #}
      <div class="modal-dialog">
      <div class="modal-content">

      </div>
    </div>
  </div>

    <h3>{{ object.subject }}</h3>
    <h3>{{ object.synopsis }}</h3>
    <h4>{{ object.text }}</h4>
    {% if object.image %}
        <img src="{{ object.image.url }}">
    {% endif %}
    <p>{{ object.owner }}  {{ object.date }}</p>

    <a href="{% url 'Blog:comment' object.id%}">
        <input type="button" value="comment">
    </a>

    {% for i in object.comments_set.all %}

        {% if i.is_published %}

        <p>{{ i.comment }}</p>
        <p>{{ i.author }}  {{ i.date }}</p>

        {% endif %}

    {% endfor %}


</body>
{% endblock %}

Blog/templates/Blog/update_posts_view.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="{% url 'Blog:update_post' object.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if object.image %}
        <img src="{{ object.image.url }}">
    {% endif %}
    {{ form.as_p }}
    <input type="submit" value="accept">
</form>

</body>
</html>

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"    {# делает красиво #}
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> {# кнопка не нажимается #}

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
          integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
          crossorigin="anonymous"></script>
  {% block extra_css %} {# кнопка не нажимается #}
  {% endblock %}    {# кнопка не нажимается #}
  {% block extra_js %}  {# кнопка не нажимается #}
  {% endblock %}    {# кнопка не нажимается  #}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" style="padding: 1px;"> {# темная шляпа #}
  <div class="collapse navbar-collapse" id="main-menu"> {# Возле красивой написи еще одна + она же ссылка #}
    <ul class="navbar-nav mr-auto">
          <p>   {# сама кнопка создания #}
            <a type="button" class="nav-link js-create-book" data-url="{% url 'Blog:feedback' %}">
              <span class="glyphicon glyphicon-plus"></span>
              Contuct us
            </a>
          </p>
    </ul>
  </div>
</nav>

<div class="container" style="padding-top: 100px;">  {# генерит все на сртаничке #}
  {% block content %}
  {% endblock %}
</div>

</body>
</html>